### ISSUE TITLE
resume download

### ISSUE THREAD

**Issue by sbinet** [otium/ytdl#1]
it should be possible to resume a previously started (but interrupted) download.

I thought the `--append,-a` option was it, but it just restarts from the beginning, appending to the previous short-file.

**Comment by otium** [comment]
This is a planned feature, haven't yet decided to just integrate it with the append flag or create a separate flag. For now it is possible to use the append flag and the range flag together, e.g. ```ytdl -a -r 100- VIDEO_URL ```

**Comment by otium** [comment]
If append is set, it will check the file for already downloaded data.
