### ISSUE TITLE
can't download videos with id that starts with a dash

### ISSUE THREAD

**Issue by denquixote** [otium/ytdl#14]
den@febf7f699c38:tmp$ ytdl https://www.youtube.com/watch?v=-KGfp2aTnHs
    INFO[0000] Fetching video info...                       
    panic: regexp: Compile(`yt.setConfig('PLAYER_CONFIG', (.*?)</script>`): error parsing regexp: missing closing ): `yt.setConfig('PLAYER_CONFIG', (.*?)</script>`

    den@febf7f699c38:tmp$ ytdl -KGfp2aTnHs
    Incorrect Usage.

    den@febf7f699c38:tmp$ ytdl -- -KGfp2aTnHs
    INFO[0000] Fetching video info...                       
    panic: regexp: Compile(`yt.setConfig('PLAYER_CONFIG', (.*?)</script>`): error parsing regexp: missing closing ): `yt.setConfig('PLAYER_CONFIG', (.*?)</script>`

Please don't judge me for my choice of an example video! :D

**Comment by denquixote** [comment]
Oh snap, I did not actually watch this video and just now I realize that this is a "log in to confirm your age" video. But I have encountered problems with other dash-id videos before. Maybe the panic that I have pasted is confusing both scenarios.

**Comment by otium** [comment]
It looks like you are using an older version. This regular expression has changed `yt.setConfig('PLAYER_CONFIG', (.*?)</script>`, and ytdl should work on age-gate videos. Update to the latest version and test if it works.

**Comment by denquixote** [comment]
Oh, indeed. I had updated with `go get -u github.com/otium/ytdl`, but it should have been `go get -u github.com/otium/ytdl/...`. The current version does work:

    den@0c84dc24db19:tmp$ ytdl -i -- -KGfp2aTnHs
    Title: [omitted]
    Author: [omitted]
    Date Published: Nov 27 2015
    Duration: 16m16s

Sorry for the noise. :)
