### ISSUE TITLE
best, worst format selectors

### ISSUE THREAD

**Issue by porjo** [otium/ytdl#2]
It would be nice if `ytdl` supported `youtube-dl`'s shortcut format selectors: `best, worst, bestvideo, bestaudio, worstvideo, worstaudio`

**Comment by otium** [comment]
Fixed in 4dc41fd8cbe1e95f9598cd513b3e34526cd5849b.
- ```-f best``` for best video and audio
- ```-f worst``` for worst video and audio
- ```-f best-video``` for best video
- ``` -f best-audio``` for best audio
- ```-f worst-video``` for worst video
- ```-f worst-audio``` for worst audio
