### ISSUE TITLE
Support downloading portions of the video

### ISSUE THREAD

**Issue by montanaflynn** [otium/ytdl#4]
My current use for `youtube-dl` is downloading videos from a specific point onwards, this isn't supported but done by using the URL provided with `-g` inside `curl` and appending the `begin` query parameter. 

Example of using the `begin` param (it's in milliseconds):

```
curl $(youtube-dl -g fjImkK1xAZI)'&begin=38000' -o kobe-block.mp4
```

There is an issue that youtube starts playing from the nearest keyframe which could be before or after the given time. My workflow now is download the video starting 10 seconds prior, run that through `ffprobe`, find the closest preceding keyframe and start the download again from there.

I am not sure that google provides an `end` or equivalent parameter but it would be useful to have that functionality as well. Ideally I'd be ably to do something like this:

```
ytdl fjImkK1xAZI --start 38 --end 42 --output --format 18 kobe-block.mp4

**Comment by otium** [comment]
I'll look into this, I wasn't aware YouTube urls supported time ranges.

**Comment by montanaflynn** [comment]
They at least support `begin`, which takes milliseconds from beginning to start at.

**Comment by otium** [comment]
I can't find any support for any end parameter, I'll consider putting in just an option for begin, but it feels incomplete without an end specifier also.

**Comment by montanaflynn** [comment]
Thanks for looking into it, I didn't find anything for end either. I think having the begin option is nice since it's undocumented and not something even `youtube-dl` does. 

I'll probably end up using `Accept-Ranges: bytes` to handle getting a trimmed video.

**Comment by otium** [comment]
```ytdl``` supports ranges, e.g. ```ytdl -r 0-100```

**Comment by montanaflynn** [comment]
There is also a query string param I noticed in the URL that appears to be the duration of the video, when I changed it I got a 403, I wonder if it has to do with the signature? 

```
dur=247.060
```

**Comment by otium** [comment]
I'll look into it
