### ISSUE TITLE
Info is confusing

### ISSUE THREAD

**Issue by amkgo** [otium/ytdl#6]
Very useful project. Thanks.

The `type Info` with method `func (*Info) Download` makes confusing. Info makes me think it's just some information about something, eg os.FileInfo. Maybe `Video` is a better name that `Info`. `Video.Downlad(...)` is better to understand.

Andrew

**Comment by otium** [comment]
I've switched back and forth between type names, I am thinking of switching it to ```VideoInfo```.

**Comment by otium** [comment]
Fixed 281cbb0
